server {
  listen 80;

  # 1. Internal Docker DNS (always this IP)
  # 'valid=5s' tells Nginx to re-check for new scaled containers every 5 seconds
  resolver 127.0.0.11 valid=5s;

  proxy_set_header X-User-Id "";
  set $auth_service "http://auth_service:3000";
  set $chat_service "http://chat_service:3001";
  set $data_service "http://data_service:3002";
  set $room_service "http://room_service:3003";
  set $auth_validate_url "http://auth_service:3000/validate";

  location = /auth-validate {
    internal; # cannot be accessed from outsite (through api call)
    proxy_pass $auth_validate_url;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-URI $request_uri;
    proxy_set_header Authorization $http_authorization;
  }

  location /auth/ {
    rewrite ^/auth/(.*)$ /$1 break;
    proxy_pass $auth_service;
    include /etc/nginx/proxy_params;
  }

  location /chat/ {

    # authorization
    auth_request /auth-validate;

    auth_request_set $user_id $upstream_http_x_user_id;
    proxy_set_header X-User-Id $user_id;

    rewrite ^/chat/(.*)$ /$1 break;
    proxy_pass $chat_service;
    include /etc/nginx/proxy_params;
    
    # WebSocket headers
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }

  location /media/ {

    # authorization
    auth_request /auth-validate;

    auth_request_set $user_id $upstream_http_x_user_id;
    proxy_set_header X-User-Id $user_id;

    rewrite ^/media/(.*)$ /$1 break;
    proxy_pass $data_service;
    include /etc/nginx/proxy_params;
  }

  location /rooms/ {
    # authorization
    auth_request /auth-validate;

    auth_request_set $user_id $upstream_http_x_user_id;
    proxy_set_header X-User-Id $user_id;

    rewrite ^/rooms/(.*)$ /$1 break;
    proxy_pass $room_service;
    include /etc/nginx/proxy_params;
  }
}